---

- name: Add nginx stable repository
  ansible.builtin.yum_repository:
    name: nginx-stable
    description: nginx stable repo
    baseurl: https://nginx.org/packages/centos/$releasever/$basearch/
    gpgcheck: true
    enabled: true
    gpgkey: https://nginx.org/keys/nginx_signing.key
    file: nginx-stable
  when: >
    ansible_os_family == 'RedHat'

- name: Install Nginx
  ansible.builtin.package:
    name:
      - nginx
      - nginx-module-acme
    state: present

- name: Configure Nginx mime types
  ansible.builtin.copy:
    src: mime.types
    dest: /etc/nginx/mime.types
    owner: root
    group: root
    mode: '0644'

- name: Create diffie hellman ephemeral parameters for nginx
  community.crypto.openssl_dhparam:
    path: /etc/nginx/ssl/dhparam.pem
    size: 2048
    owner: root
    group: root
    mode: '0640'

- name: Configure Nginx
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0640'
  notify: Reload Nginx

- name: Install SElinux config libs
  ansible.builtin.package:
    name: python3-libsemanage
  when: >
    ansible_os_family == 'RedHat'
    and ansible_distribution_major_version >= '8'

- name: Allow httpd to act as reverse proxy
  ansible.posix.seboolean:
    name: httpd_can_network_relay
    state: true
    persistent: true
  when: >
    ansible_distribution == 'CentOS'
    or ansible_distribution == 'RedHat'
    or ansible_distribution == 'Scientific'

- name: Start and enable nginx
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started
