---

- name: Fail early if OS is not supported
  ansible.builtin.assert:
    that: ansible_os_family == 'Debian'

- name: Install opencast dependencies
  ansible.builtin.package:
    name:
      - openjdk-21-jre-headless
      - curl
      - ffmpeg-dist
      - netcat
      - opensearch
      - opensearch-analysis-icu
      - tesseract-ocr
      - tesseract-ocr-deu
      # for ingest script
      - python3
      - python3-requests
      - python3-yaml

- name: Set default java
  community.general.alternatives:
    name: java
    family: /usr/lib/jvm/java-{{ java_version }}-openjdk-amd64/bin/java
    state: selected
