---

###
# Install Opencast RPM repositories

- name: Install Opencast dependencies
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Opencast dependencies
  ansible.builtin.include_tasks: el9.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '9'

###
# Configure OpenSearch

- name: OpenSearch Install | Copy Configuration File
  ansible.builtin.blockinfile:
    block: |
      cluster.name: "opensearch-cluster"
      node.name: "{{ inventory_hostname }}"
      network.host: "127.0.0.1"
      http.port: "9200"
      discovery.type: single-node
      bootstrap.memory_lock: true
      plugins.security.disabled: true
    dest: /etc/opensearch/opensearch.yml
    state: present
    create: true
    marker: "## {mark} opensearch main configuration ##"
    owner: "opensearch"
    group: "opensearch"
    mode: "0600"

###
# Create opencast directories

- name: Create Opencast directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '0775'
    owner: opencast
    group: opencast
  loop:
    - /srv/opencast
    - /opt/opencast-build

###
# Install build and ingest scripts, install systemd service files

- name: Install Opencast build and ingest scripts
  ansible.builtin.template:
    src: '{{ item }}'
    dest: /opt/opencast-build/
    mode: '0750'
    owner: opencast
    group: opencast
  loop:
    - opencast-build.sh
    - media.yml
    - ingest.py

- name: Install Systemd service files
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: /etc/systemd/system/
    mode: '0644'
    owner: root
    group: root
    force: true
  loop:
    - opencast.service
    - opencast-build.service
    - opencast-build.timer

- name: Give Opencast user rights to run build commands with higher privileges
  ansible.builtin.copy:
    src: opencast-build-sudoers
    dest: /etc/sudoers.d/
    mode: '0440'
    owner: root
    group: root
    force: true

###
# Enable and run opencast buid service

- name: Enable Opencast build service
  ansible.builtin.systemd:
    daemon_reload: true
    name: opencast-build.timer
    enabled: true
    state: started

- name: Enable opencast service
  ansible.builtin.service:
    name: opencast
    enabled: true

- name: Run Opencast build service
  ansible.builtin.service:
    name: opencast-build.service
    state: started
