all:
  hosts:
    develop.opencast.org:
      # for repository:
      opencast_version_major: 20
      # for tarball:
      version: 20-SNAPSHOT
      java_version: 21
    stable.opencast.org:
      opencast_version_major: 19
      version: 19-SNAPSHOT
      java_version: 21
    legacy.opencast.org:
      opencast_version_major: 18
      version: 18-SNAPSHOT
      java_version: 21
  vars:
    opencast_repository_enabled_release: true
    opencast_repository_enabled_testing: true
