---
roles:
  - name: lkiesow.dnf_autoupdate
    version: 2.0.1
  - name: lkiesow.apt_autoupdate
    version: 1.0.0
  - name: elan.opencast_firewalld
    version: v0.1.0
  - name: elan.opencast_repository
    version: v0.1.0
  - name: elan.opencast_user
    version: v0.1.0

collections:
  - community.crypto
