---
# vim: et:ts=2:sw=2:sts=2
# This playbook deploys a Buildbot master and worker(s) configured for Opencast

- hosts: s3
  gather_facts: false
  user: "{{ login_user }}"
  roles:
    - { role: s3-server, when: "hostvars[inventory_hostname]['deploy_s3_server'] | bool" }

- hosts: buildbot
  gather_facts: false
  user: "{{ login_user }}"
  roles:
    - { role: buildbot-base }
    - { role: geerlingguy.docker, become: true }
    - { role: docker-tcp-connectable }
    - { role: buildbot-keysync, tags: [ rekey ] }
    - { role: autossh, when: "'master' not in group_names", tags: [ rekey ] }
    - { role: buildbot-id-mapping, tags: [ buildbot, reconfig ] }
  handlers:
    - import_tasks: handlers/handlers.yml

- hosts: master
  gather_facts: false
  user: "{{ login_user }}"
  roles:
    - { role: certbot-init, become: yes }
    - { role: geerlingguy.certbot, become: yes }
  handlers:
    - import_tasks: handlers/handlers.yml

- hosts: master
  gather_facts: false
  user: "{{ login_user }}"
  roles:
    - { role: buildbot-master-install, tags: [ buildbot ] }
  handlers:
    - import_tasks: handlers/handlers.yml

- hosts: workers
  gather_facts: false
  user: "{{ login_user }}"
  roles:
    - { role: buildbot-worker, tags: [ buildbot ] }
  handlers:
    - import_tasks: handlers/handlers.yml

- hosts: all
  gather_facts: false
  user: "{{ login_user }}"
  roles:
    - { role: buildbot-config, tags: [ buildbot, reconfig ] }
  handlers:
    - import_tasks: handlers/handlers.yml

- hosts: workers
  gather_facts: false
  user: "{{ login_user }}"
  roles:
    - { role: buildbot-new-images, tags: [ buildbot, reconfig ] }
  handlers:
    - import_tasks: handlers/handlers.yml
